### ISSUE TITLE
【未分叉页面】块详情中age 一列应该是右对齐。

### ISSUE THREAD

**Issue by gengzhihui** [btccom/eth-fork-constantin#11]
高保真：

![image](https://user-images.githubusercontent.com/16459498/50887608-9b6a5900-142e-11e9-805e-22bea89d9fdb.png)

实际效果：
![image](https://user-images.githubusercontent.com/16459498/50887592-92798780-142e-11e9-8972-b24a9d43151f.png)

**Comment by rumsky** [comment]
和 eth 浏览器保持一致 之前都是左对齐
