### ISSUE TITLE
【Ethereum Block Rewards Chart详情页】safari／火狐／edge下载图表显示不全

### ISSUE THREAD

**Issue by gengzhihui** [btccom/eth-fork-constantin#16]
操作步骤：
1、在safari／火狐／edge浏览器中，下载图表，形式不是下载，是在新的标签页打开该图。
2、下载的如截图所示：标题没有，时间维度没有，画面还不清晰。
![image](https://user-images.githubusercontent.com/16459498/50890612-7cbb9080-1435-11e9-9c1e-22859ec6a9d5.png)

**Comment by rumsky** [comment]
经和产品确认 下载图片按钮去掉
