### ISSUE TITLE
【区块播报奖励】上方图标的链接是否需要更改

### ISSUE THREAD

**Issue by gengzhihui** [btccom/eth-fork-constantin#22]
![image](https://user-images.githubusercontent.com/16459498/50943336-f94a7f80-14c6-11e9-8445-926c3e654f84.png)

目前效果：
1、点击图标1:进入的是eth.btc.com
2、点击图标2:进入的是分叉的首页面。

因为考虑到用户的习惯问题，我会认为点1:进入的是btc.com
点击2，进入的是eth.btc.com

**Comment by rumsky** [comment]
重复问题 [https://github.com/btccom/eth-fork-constantin/issues/22](url)
