### ISSUE TITLE
【每笔交易平均gas使用统计图】当时间维度为小时时，竖线横切面效果是一个时间段，不是时间点。

### ISSUE THREAD

**Issue by gengzhihui** [btccom/eth-fork-constantin#25]
实际效果：
![image](https://user-images.githubusercontent.com/16459498/50944076-f4d39600-14c9-11e9-88aa-354115d1db07.png)

原型图中展示的是一个时间间隔：
![image](https://user-images.githubusercontent.com/16459498/50944096-03ba4880-14ca-11e9-9828-a76b577882fc.png)

**Comment by rumsky** [comment]
已和产品确认 显示为时间点
