### ISSUE TITLE
【刷新】当从图表详情页，返回到首页时，爆块没出来时，建议一个刷新的loading图标

### ISSUE THREAD

**Issue by gengzhihui** [btccom/eth-fork-constantin#29]
建议某个地方没有显示出数据，有一个刷新的图标。
![image](https://user-images.githubusercontent.com/16459498/50946816-39652e80-14d6-11e9-955b-e5dfc31fa950.png)
![image](https://user-images.githubusercontent.com/16459498/50946844-5c8fde00-14d6-11e9-9dbe-9dbbe4844c79.png)

**Comment by rumsky** [comment]
No data 改为 Loading...

**Comment by gengzhihui** [comment]
有时候图表也不出来，可否也加一个loading...啊
