### ISSUE TITLE
【手机端】图表错误

### ISSUE THREAD

**Issue by gengzhihui** [btccom/eth-fork-constantin#37]
操作步骤：
1、当手指固定在图表的某个原点处，不太容易弹出竖线横切线。
2、如果弹出竖线横切线后，显示不全，有遮挡。
![01f8c9c9627033c9ce49fc912651a1d7](https://user-images.githubusercontent.com/16459498/50959778-b3111280-14fe-11e9-8b3f-9224403b12b1.png)

**Comment by rumsky** [comment]
移动端去掉tooltip
