### ISSUE TITLE
【UI】字体-建议重要文案统一 fontweight ：600

### ISSUE THREAD

**Issue by wanghongshu** [btccom/eth-fork-constantin#6]
箭头所指四行的文字都是重要文字，目前粗细不一致，建议字体粗细一致600
<img width="925" alt="qq20190109-161802 2x" src="https://user-images.githubusercontent.com/29766981/50886029-56dcbe80-142a-11e9-8627-1b06ba409d34.png">

**Comment by gengzhihui** [comment]
![image](https://user-images.githubusercontent.com/16459498/51016251-99c5a000-15aa-11e9-9a3d-1b00b4137845.png)
